services:
    socket-proxy:
        image: lscr.io/linuxserver/socket-proxy:latest
        container_name: socket-proxy
        environment:
            - ALLOW_START=0
            - ALLOW_STOP=0
            - ALLOW_RESTARTS=0
            - AUTH=0
            - BUILD=0
            - COMMIT=0
            - CONFIGS=0
            - CONTAINERS=1
            - DISABLE_IPV6=0
            - DISTRIBUTION=0
            - EVENTS=1
            - EXEC=0
            - IMAGES=0
            - INFO=0
            - NETWORKS=0
            - NODES=0
            - PING=1
            - PLUGINS=0
            - POST=0
            - PROXY_READ_TIMEOUT=240
            - SECRETS=0
            - SERVICES=0
            - SESSION=0
            - SWARM=0
            - SYSTEM=0
            - TASKS=0
            - VERSION=1
            - VOLUMES=0
        ports:
            - 2377:2375
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        read_only: true
        tmpfs:
            - /run
