services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      
    volumes:
      - ./data-vw:/data
    ports:
      - 985:80
    env_file:
    - .env
volumes:
  vw-data: null
