name: forgejo

services:
    forgejo:
        container_name: forgejo
        restart: always
        image: codeberg.org/forgejo/forgejo:10 # pinned to major ver to avoid issues
        networks:
            - forgejo
        volumes:
            - ../../data/forgejo/forgejo:/data
            - /etc/timezone:/etc/timezone
            - /etc/localtime:/etc/localtime
        ports:
            - 1:3000
        depends_on:
            - db
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - FORGEJO__database__DB_TYPE=postgres
            - FORGEJO__database__HOST=db:5432
            - FORGEJO__database__NAME=forgejo
            - FORGEJO__database__USER=postgres
            - FORGEJO__database__PASSWD=postgres
        env_file:
            - .env
    db:
        container_name: forgejo-db
        restart: always
        image: postgres:14 # pinned as it is the data version. DO NOT UNPIN!!!
        environment: # hardcoded because who cares
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=forgejo
        user: "1000:1000"
        networks:
            - forgejo
        volumes:
            - ../../data/forgejo/db:/var/lib/postgresql/data
networks:
    forgejo: null
