name: forgejo

services:
    forgejo:
        container_name: forgejo
        restart: always
        image: codeberg.org/forgejo/forgejo:10
        networks:
            - forgejo
        volumes:
            - ../../data/forgejo/forgejo:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 1:3000
        depends_on:
            - db
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - FORGEJO__database__DB_TYPE=postgres
            - FORGEJO__database__HOST=db:5432
            - FORGEJO__database__NAME=forgejo
            - FORGEJO__database__USER=forgejo
            - FORGEJO__database__PASSWD=forgejo
        env_file:
            - .env
    db:
        container_name: forgejo-db
        restart: always
        image: postgres:14
        environment: # hardcoded because who cares
            - POSTGRES_USER=forgejo
            - POSTGRES_PASSWORD=forgejo
            - POSTGRES_DB=forgejo
        user: "1000:1000"
        networks:
            - forgejo
        volumes:
            - ../../data/forgejo/db:/var/lib/postgresql/data
networks:
    forgejo: null
