services:
    web:
        image: mediawiki
        container_name: mediawiki
        ports:
            - 6928:80
        volumes:
            - ../../data/LocalSettings.php:/var/www/html/LocalSettings.php
            - ../../data/mw-data:/var/www/data
            - ../../data/mw-images:/var/www/html/images
