name: eufy-ws
services:
    eufy-security-ws:
        network_mode: host
        stdin_open: true
        tty: true
        environment:
            - PORT=8371
        volumes:
            - "./data-eufyws:/data"
        image: bropat/eufy-security-ws:latest
        restart: unless-stopped
        env_file:
            - .env
volumes:
    eufy-ws-data:
