version: "3.3"
services:
  wakapi:
    volumes:
      - ./data-wakapi:/data
    container_name: wakapi
    image: ghcr.io/muety/wakapi:latest
    restart: always
    ports:
      - 145:3000
    env_file:
    - .env
volumes:
  wakapi-data: {}
