name: hass

services:
    hass:
        container_name: hass
        restart: unless-stopped
        image: ghcr.io/home-assistant/home-assistant:stable
        volumes:
            - ../../data/hass:/config
            - /etc/localtime:/etc/localtime
            - /run/dbus:/run/dbus
        privileged: true
        network_mode: service:tailscale
    tailscale:
        container_name: tailscale-hass
        image: tailscale/tailscale:latest
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_EXTRA_ARGS=--advertise-tags=tag:container --hostname=homeassistant --ssh
        env_file:
            - ../../.tskey
        volumes:
            - ../../data/tailscale-hass:/var/lib/tailscale
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
            - sys_module
        restart: unless-stopped
        network_mode: host
