name: hass

services:
    hass:
        container_name: hass
        restart: unless-stopped
        image: ghcr.io/home-assistant/home-assistant:stable
        volumes:
            - ../../data/hass:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        privileged: true
        network_mode: host # runs with host network to be able to scan for devices. port is 8123 by default
