name: dash

services:
    dash:
        image: mauricenino/dashdot:latest
        restart: unless-stopped
        privileged: true
        volumes:
            - /:/mnt/host:ro
        environment:
            - DASHDOT_ENABLE_CPU_TEMPS=true
        ports:
            - 3001:3001
