version: "3.8"
services:
    web:
        restart: always
        container_name: redlib
        ports:
            - 245:8080
        user: nobody
        read_only: true
        security_opt:
            - no-new-privileges:true
        env:
            - REDLIB_DEFAULT_THEME=rosebox
        cap_drop:
            - ALL
        healthcheck:
            test:
                - CMD
                - wget
                - --spider
                - -q
                - --tries=1
                - http://localhost:8080/settings
            interval: 5m
            timeout: 3s
        image: quay.io/redlib/redlib:latest-arm
        env_file:
            - .env
