name: adguard-home

services:
    adguard-home:
        container_name: adguard-home
        user: "1000:1000"
        image: adguard/adguardhome:latest
        cap_add:
            - CAP_NET_BIND_SERVICE
        ports:
            - 53:53/tcp # plain dns over tcp
            - 53:53/udp # plain dns over udp
            - 6970:80/tcp # http web interface
            - 6971:3000/tcp # initial setup web interface
        volumes:
            - ../../data/adguard-home/config:/opt/adguardhome/conf # app configuration
            - ../../data/adguard-home/work:/opt/config