name: adguard-home

services:
    adguard-home:
        container_name: adguard-home
        user: "1000:1000"
        image: adguard/adguardhome:latest
        cap_add:
            - CAP_NET_BIND_SERVICE
        volumes:
            - ../../data/adguard-home/config:/opt/adguardhome/conf # app configuration
            - ../../data/adguard-home/work:/opt/config
        network_mode: service:tailscale
    tailscale:
        container_name: tailscale-adguard-home
        image: tailscale/tailscale:latest
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_EXTRA_ARGS=--advertise-tags=tag:container --hostname=adguard --ssh
        env_file:
            - ../../.tskey
        volumes:
            - ../../data/tailscale-adguard-home:/var/lib/tailscale
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
            - sys_module
        restart: unless-stopped
