version: '3.3'
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - '4242:8080'
    volumes:
      - ./data-trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./data-extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
    restart: unless-stopped
    env_file:
        - .env